export const GET_CHAPTERS = "GET_CHAPTERS";
export const FIND_CHAPTER = "FIND_CHAPTER";
export const DELETE_CHAPTERS = "DELETE_CHAPTERS";
export const UPDATE_CHAPTERS = "UPDATE_CHAPTERS";
export const ADD_CHAPTER = "ADD_CHAPTER";
